---
- hosts: all
  gather_facts: no
  become: yes
  roles:
    - common
    - TS5000
    - zerotier
    - tcpdumpd
    - syslog
    - iperf
    - zabbix-server
    - cockpit
    - apache-proxy
    - index-html

